RAW_DATA_RESAMPLE_MIN = 5
ANOMALY_RESAMPLE_MIN = 5
FUTURE_PREDICTION_RESAMPLE_MIN = 10

FUTURE_PREDICTION_INPUT_STEP = 72
FUTURE_PREDICTION_OUTPUT_STEP = 48
FUTURE_PREDICTION_ALPHA = 0.1

SURVIVAL_N_PREDICTION = 365

OUTLIER_SIGMA = 3
TEMP_FOLDER = 'temp'

UNIT_NAME_MAPPER = {
    'PLTU Pacitan 1': 'UJPCT1'
}